#!/usr/bin/env python
"""
    globifest/build - globifest Command Line Utility

    This script allows command-line execution of the Builder.

    Copyright 2018, Daniel Kristensen, Garmin Ltd, or its subsidiaries.
    All rights reserved.

    Redistribution and use in source and binary forms, with or without
    modification, are permitted provided that the following conditions are met:

    * Redistributions of source code must retain the above copyright notice, this
      list of conditions and the following disclaimer.

    * Redistributions in binary form must reproduce the above copyright notice,
      this list of conditions and the following disclaimer in the documentation
      and/or other materials provided with the distribution.

    * Neither the name of the copyright holder nor the names of its
      contributors may be used to endorse or promote products derived from
      this software without specific prior written permission.

    THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
    AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
    IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
    DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE
    FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
    DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
    SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
    CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY,
    OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
    OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
"""

import argparse
import re
import sys

# Import GlobifestLib and modules
import GlobifestLib
from GlobifestLib import *

def run_cmd():
    """
    Run the command line utility

    @return 0 if build was successful, or error code otherwise
    @returntype int
    """

    parser = argparse.ArgumentParser(
        formatter_class = argparse.RawDescriptionHelpFormatter,
        description = "Global Package Manifest Builder",
        fromfile_prefix_chars="@",
        epilog =
        "Confguration examples:\n"
        "    os=\"linux\" module=\"foobaz\"\n"
        "    max_threads=1\n"
        "    do_logging  (evaluates to empty string)\n"
        "    text=\"This is all one value\"\n"
        "    @my_settings.cfg  (imports settings from my_settings.cfg)\n"
        )
    parser.add_argument(
        "-i","--input",
        help = "package file to parse",
        action="store",
        dest="in_fname",
        type=str,
        metavar="fname",
        required=True
        )

    parser.add_argument(
        "-o","--output",
        help = "Where to save output",
        action="store",
        dest="out_fname",
        type=str,
        metavar="name",
        required=True
        )

    parser.add_argument(
        "--pre",
        help="Prefix to print before the list of entries in the output (default=\"\")",
        action="store",
        dest="pre",
        type=str,
        default="",
        metavar="text"
        )

    parser.add_argument(
        "--format",
        help="Format string to apply to each entry in the output (default=\"{}\\n\")\n"
            "The items appear as follows:\n"
            "    {} = Entry text (header file, etc...)",
        action="store",
        dest="format_str",
        type=str,
        default="{}\n",
        metavar="format"
        )

    parser.add_argument(
        "--post",
        help="Suffix to print after the list of entries in the output (default=\"\")",
        action="store",
        dest="post",
        type=str,
        default="",
        metavar="text"
        )

    parser.add_argument(
        "-v","--verbose",
        help="Print verbose output to stdout (0=None (default), 1=Basic, 2=Verbose, 3=Extreme)",
        action="store",
        dest="verbose",
        type=int,
        default=0,
        metavar="level"
        )

    parser.add_argument(
        help="Configuration options",
        nargs="*",
        dest="configlist",
        type=str,
        metavar="variable=value"
        )

    args = parser.parse_args()

    Log.Logger.set_level(args.verbose)

    try:

        Log.D("In:      {}".format(args.in_fname))
        Log.D("Out:     {}".format(args.out_fname))
        Log.D("Pre:     {}".format(args.pre))
        Log.D("Format:  {}".format(args.format_str))
        Log.D("Post:    {}".format(args.post))

        pair_regex = re.compile("([^=]*)=\"?(.*?)\"?$", re.MULTILINE)
        single_regex = re.compile("([^=]*)", re.MULTILINE)

        manifest_configs=Util.Container()

        Log.D("Configs:")
        for config in args.configlist:
            m = pair_regex.fullmatch(config)
            if m:
                # Pair config
                manifest_configs[m.group(1)] = m.group(2)
            else:
                m = single_regex.fullmatch(config)
                if m:
                    manifest_configs[m.group(1)] = None

            if m:
                value = manifest_configs[m.group(1)]
                Log.D("  {} = {}({})".format(m.group(1), type(value).__name__, value))
                pass
            else:
                Log.E("Invalid config: {}".format(config), Log.ERROR.INPUT)

        manifest = Builder.build_manifest(args.in_fname, ConfigSet.new(manifest_configs))
    except Log.GlobifestException as e:
        # The logger prints these already, no need to print again
        print("FAILED")
        return e.get_type()

    print("MANIFEST_OUTPUT:")
    print(manifest.get_output())
    #TODO: Build an output file with this

    return 0

if __name__ == "__main__":
    exit( run_cmd() )
