#!/usr/bin/env python
"""
    globifest/config - globifest Configuration Application

    Copyright 2018, Daniel Kristensen, Garmin Ltd, or its subsidiaries.
    All rights reserved.

    Redistribution and use in source and binary forms, with or without
    modification, are permitted provided that the following conditions are met:

    * Redistributions of source code must retain the above copyright notice, this
      list of conditions and the following disclaimer.

    * Redistributions in binary form must reproduce the above copyright notice,
      this list of conditions and the following disclaimer in the documentation
      and/or other materials provided with the distribution.

    * Neither the name of the copyright holder nor the names of its
      contributors may be used to endorse or promote products derived from
      this software without specific prior written permission.

    THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
    AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
    IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
    DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE
    FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
    DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
    SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
    CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY,
    OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
    OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
"""

import argparse
import os
import sys

from Globiconfig import Main
from GlobifestLib import Util

def parse_args():
    """Parse command-line arguments and return the results"""

    parser = argparse.ArgumentParser(
        description="Globifest Configuration Utility",
        prefix_chars="-/",
        fromfile_prefix_chars="@"
        )

    # Additional help options; but no need to clutter up the help text
    parser.add_argument(
        "-?", "/?",
        help=argparse.SUPPRESS,
        action="help"
        )

    parser.add_argument(
        "-o","--out",
        help="Output directory (attempts to find automatically if not given)",
        action="store",
        default="",
        metavar="dir"
        )

    parser.add_argument(
        "project",
        help="Project file",
        action="store",
        nargs="?",
        default=""
        )

    return parser.parse_args()

if __name__ == "__main__":
    args = parse_args()
    if args.project:
        args.project = Util.get_abs_path(args.project, os.getcwd())

        # if a project name is specified, but not an output directory,
        # attempt to find it
        if not args.out:
            # Look for a folder named "out" in:
            # 1. The project file's directory
            # 2. The current working directory
            search_paths = [os.path.dirname(args.project), os.getcwd()]
            for path in search_paths:
                for dir_ent in os.listdir(path=path):
                    if not os.path.isdir(dir_ent):
                        continue

                    dir_name = os.path.basename(dir_ent)
                    if dir_name.find("out") != -1:
                        args.out = dir_name
                        print("Auto-detected output directory {}".format(dir_name))
                        break
    app = Main.App(args.project, args.out)
    sys.exit(app.run())
