"""
    generators/gen_json.py - Globifest generator for JSON-formatted config data

    Copyright 2019, Daniel Kristensen, Garmin Ltd, or its subsidiaries.
    All rights reserved.

    Redistribution and use in source and binary forms, with or without
    modification, are permitted provided that the following conditions are met:

    * Redistributions of source code must retain the above copyright notice, this
      list of conditions and the following disclaimer.

    * Redistributions in binary form must reproduce the above copyright notice,
      this list of conditions and the following disclaimer in the documentation
      and/or other materials provided with the distribution.

    * Neither the name of the copyright holder nor the names of its
      contributors may be used to endorse or promote products derived from
      this software without specific prior written permission.

    THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
    AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
    IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
    DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE
    FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
    DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
    SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
    CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY,
    OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
    OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
"""

import json
import os

if __name__ == "<globifest>":
    # Disable pylint warnings for symbols being provided by Globifest
    OUT_FILE = OUT_FILE # pylint:disable=E0602
    OUT_DIR = OUT_DIR # pylint:disable=E0602
    DEFINITIONS = DEFINITIONS # pylint:disable=E0602
    PARAM_TYPE = PARAM_TYPE # pylint:disable=E0602
    g_err = g_err # pylint:disable=E0602
    g_print = g_print # pylint:disable=E0602

    g_print("Generating JSON file: {}".format(OUT_FILE))

    os.makedirs(os.path.dirname(OUT_FILE), exist_ok=True)

    with open(OUT_FILE, mode="wt") as json_file:
        encoder = json.JSONEncoder(
            allow_nan=False,
            indent=2,
            sort_keys=True
            )
        value_list = []
        for entry in DEFINITIONS:
            ptype = entry.param.get_type()
            value = entry.value

            for implicit_entry in entry.param.get_implicit_values():
                value_list.append(dict(
                    id=implicit_entry[0],
                    type=PARAM_TYPE.enum_id[PARAM_TYPE.INT],
                    value=implicit_entry[1]
                    ))
            if ptype == PARAM_TYPE.BOOL:
                value = (value != "FALSE")
            elif ptype in [PARAM_TYPE.FLOAT]:
                value = float(value)
            elif ptype in [PARAM_TYPE.INT]:
                value = int(value)
            elif ptype not in [PARAM_TYPE.STRING, PARAM_TYPE.ENUM]:
                g_err("Unhandled type {}".format(ptype))
            value_list.append(dict(
                id=entry.param.get_identifier(),
                type=PARAM_TYPE.enum_id[entry.param.get_type()],
                value=value
                ))

        json_file.write(encoder.encode(
            dict(
                __HEADER__="GENERATED BY GLOBIFEST - DO NOT EDIT",
                settings=value_list
                )
            ))
